#!/bin/sh
CURPWD=$PWD
mkdir $HOME/.vegastrike
cd $HOME/.vegastrike
if cat save.4.x.txt 2> /dev/null ;
then
	touch save.4.x.txt;
else
	echo "default"> save.4.x.txt ;
fi
cp /usr/share/vegastrike/data/setup.config .
cp /usr/share/vegastrike/data/.vegastrike/*.m3u .
cp /usr/share/vegastrike/data/vegastrike.config .
/usr/bin/vssetup
echo "If you wish to have your own music edit ~/.vegastrike/*.m3u  Each playlist represents a place or situation in Vega Strike"
cd $CURPWD
